CREATE TABLE IF NOT EXISTS booking_details (
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    booking_id uuid NOT NULL REFERENCES bookings(id) ON DELETE CASCADE,
    item_type varchar(20) NOT NULL CHECK (item_type IN ('PACKAGE','COMBO','ADDON')),
    ref_id uuid NOT NULL,
    snapshot_name varchar(100) NOT NULL,
    snapshot_price bigint NOT NULL CHECK (snapshot_price >= 0),
    quantity integer NOT NULL DEFAULT 1 CHECK (quantity > 0),
    subtotal bigint NOT NULL CHECK (subtotal >= 0),
    duration_minutes integer NOT NULL DEFAULT 0 CHECK (duration_minutes >= 0),
    sort_order integer NOT NULL DEFAULT 0,
    created_at timestamp(6) with time zone NOT NULL DEFAULT now(),
    PRIMARY KEY (id)
);

ALTER TABLE booking_details ADD COLUMN IF NOT EXISTS booking_id uuid REFERENCES bookings(id) ON DELETE CASCADE;
ALTER TABLE booking_details ADD COLUMN IF NOT EXISTS item_type varchar(20) NOT NULL DEFAULT 'PACKAGE';
ALTER TABLE booking_details ADD COLUMN IF NOT EXISTS ref_id uuid;
ALTER TABLE booking_details ADD COLUMN IF NOT EXISTS snapshot_name varchar(100) NOT NULL DEFAULT 'Demo item';
ALTER TABLE booking_details ADD COLUMN IF NOT EXISTS snapshot_price bigint NOT NULL DEFAULT 0;
ALTER TABLE booking_details ADD COLUMN IF NOT EXISTS quantity integer NOT NULL DEFAULT 1;
ALTER TABLE booking_details ADD COLUMN IF NOT EXISTS subtotal bigint NOT NULL DEFAULT 0;
ALTER TABLE booking_details ADD COLUMN IF NOT EXISTS duration_minutes integer NOT NULL DEFAULT 0;
ALTER TABLE booking_details ADD COLUMN IF NOT EXISTS sort_order integer NOT NULL DEFAULT 0;
ALTER TABLE booking_details ADD COLUMN IF NOT EXISTS created_at timestamp(6) with time zone NOT NULL DEFAULT now();

CREATE INDEX IF NOT EXISTS idx_booking_details_booking_id ON booking_details (booking_id);
CREATE INDEX IF NOT EXISTS idx_booking_details_ref_id ON booking_details (ref_id);
CREATE INDEX IF NOT EXISTS idx_booking_details_item_type ON booking_details (item_type);
CREATE UNIQUE INDEX IF NOT EXISTS uq_one_primary_item_per_booking
ON booking_details (booking_id)
WHERE item_type IN ('PACKAGE', 'COMBO');

CREATE TABLE IF NOT EXISTS booking_pricing (
    booking_id uuid NOT NULL REFERENCES bookings(id) ON DELETE CASCADE,
    subtotal bigint NOT NULL DEFAULT 0 CHECK (subtotal >= 0),
    estimated_duration_minutes integer NOT NULL DEFAULT 0 CHECK (estimated_duration_minutes >= 0),
    discount_type varchar(20) CHECK (discount_type IN ('VOUCHER','PROMOTION')),
    discount_ref_id uuid,
    discount_ref_snapshot varchar(255),
    discount_amount bigint NOT NULL DEFAULT 0 CHECK (discount_amount >= 0),
    final_amount bigint NOT NULL DEFAULT 0 CHECK (final_amount >= 0),
    updated_at timestamp(6) with time zone NOT NULL DEFAULT now(),
    PRIMARY KEY (booking_id)
);

ALTER TABLE booking_pricing ADD COLUMN IF NOT EXISTS subtotal bigint NOT NULL DEFAULT 0;
ALTER TABLE booking_pricing ADD COLUMN IF NOT EXISTS estimated_duration_minutes integer NOT NULL DEFAULT 0;
ALTER TABLE booking_pricing ADD COLUMN IF NOT EXISTS discount_type varchar(20);
ALTER TABLE booking_pricing ADD COLUMN IF NOT EXISTS discount_ref_id uuid;
ALTER TABLE booking_pricing ADD COLUMN IF NOT EXISTS discount_ref_snapshot varchar(255);
ALTER TABLE booking_pricing ADD COLUMN IF NOT EXISTS discount_amount bigint NOT NULL DEFAULT 0;
ALTER TABLE booking_pricing ADD COLUMN IF NOT EXISTS final_amount bigint NOT NULL DEFAULT 0;
ALTER TABLE booking_pricing ADD COLUMN IF NOT EXISTS updated_at timestamp(6) with time zone NOT NULL DEFAULT now();

CREATE UNIQUE INDEX IF NOT EXISTS uq_booking_pricing_booking_id ON booking_pricing (booking_id);

CREATE TABLE IF NOT EXISTS booking_status_histories (
    changed_at timestamp(6) with time zone NOT NULL DEFAULT now(),
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    booking_id uuid NOT NULL REFERENCES bookings(id),
    changed_by uuid REFERENCES users(id),
    new_status varchar(30) NOT NULL,
    old_status varchar(30),
    reason varchar(255),
    PRIMARY KEY (id)
);

ALTER TABLE booking_status_histories ADD COLUMN IF NOT EXISTS changed_at timestamp(6) with time zone NOT NULL DEFAULT now();
ALTER TABLE booking_status_histories ADD COLUMN IF NOT EXISTS booking_id uuid REFERENCES bookings(id);
ALTER TABLE booking_status_histories ADD COLUMN IF NOT EXISTS changed_by uuid REFERENCES users(id);
ALTER TABLE booking_status_histories ADD COLUMN IF NOT EXISTS new_status varchar(30) NOT NULL DEFAULT 'PENDING';
ALTER TABLE booking_status_histories ADD COLUMN IF NOT EXISTS old_status varchar(30);
ALTER TABLE booking_status_histories ADD COLUMN IF NOT EXISTS reason varchar(255);

CREATE INDEX IF NOT EXISTS idx_booking_status_histories_booking_id ON booking_status_histories (booking_id);

CREATE TABLE IF NOT EXISTS wash_sessions (
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    booking_id uuid NOT NULL REFERENCES bookings(id) ON DELETE CASCADE,
    assigned_staff_id uuid REFERENCES users(id) ON DELETE SET NULL,
    fee_amount bigint,
    projected_points integer,
    awarded_points integer,
    checked_in_at timestamp(6) with time zone,
    started_at timestamp(6) with time zone,
    completed_at timestamp(6) with time zone,
    cancelled_at timestamp(6) with time zone,
    created_at timestamp(6) with time zone NOT NULL DEFAULT now(),
    cancel_fault_type varchar(30) CHECK (cancel_fault_type IN ('CARWASH_FAULT','CUSTOMER_FAULT')),
    cancel_reason varchar(500),
    notes text,
    status varchar(20) NOT NULL CHECK (status IN ('PENDING','QUEUED','CHECKED_IN','IN_PROGRESS','COMPLETED','CANCELLED')),
    PRIMARY KEY (id)
);

ALTER TABLE wash_sessions ADD COLUMN IF NOT EXISTS booking_id uuid REFERENCES bookings(id) ON DELETE CASCADE;
ALTER TABLE wash_sessions ADD COLUMN IF NOT EXISTS assigned_staff_id uuid REFERENCES users(id) ON DELETE SET NULL;
ALTER TABLE wash_sessions ADD COLUMN IF NOT EXISTS fee_amount bigint;
ALTER TABLE wash_sessions ADD COLUMN IF NOT EXISTS projected_points integer;
ALTER TABLE wash_sessions ADD COLUMN IF NOT EXISTS awarded_points integer;
ALTER TABLE wash_sessions ADD COLUMN IF NOT EXISTS checked_in_at timestamp(6) with time zone;
ALTER TABLE wash_sessions ADD COLUMN IF NOT EXISTS started_at timestamp(6) with time zone;
ALTER TABLE wash_sessions ADD COLUMN IF NOT EXISTS completed_at timestamp(6) with time zone;
ALTER TABLE wash_sessions ADD COLUMN IF NOT EXISTS cancelled_at timestamp(6) with time zone;
ALTER TABLE wash_sessions ADD COLUMN IF NOT EXISTS created_at timestamp(6) with time zone NOT NULL DEFAULT now();
ALTER TABLE wash_sessions ADD COLUMN IF NOT EXISTS cancel_fault_type varchar(30);
ALTER TABLE wash_sessions ADD COLUMN IF NOT EXISTS cancel_reason varchar(500);
ALTER TABLE wash_sessions ADD COLUMN IF NOT EXISTS notes text;
ALTER TABLE wash_sessions ADD COLUMN IF NOT EXISTS status varchar(20) NOT NULL DEFAULT 'PENDING';

CREATE INDEX IF NOT EXISTS idx_wash_sessions_booking_id ON wash_sessions (booking_id);
CREATE INDEX IF NOT EXISTS idx_wash_sessions_assigned_staff_id ON wash_sessions (assigned_staff_id);
CREATE INDEX IF NOT EXISTS idx_wash_sessions_status ON wash_sessions (status);

CREATE TABLE IF NOT EXISTS payments (
    amount bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL DEFAULT now(),
    paid_at timestamp(6) with time zone,
    booking_id uuid NOT NULL UNIQUE REFERENCES bookings(id),
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    transaction_ref varchar(120),
    method varchar(30) NOT NULL CHECK (method IN ('CASH_AT_COUNTER','BANK_TRANSFER','E_WALLET')),
    status varchar(20) NOT NULL CHECK (status IN ('UNPAID','PENDING_PAYMENT','PAID','FAILED','REFUNDED')),
    PRIMARY KEY (id)
);

ALTER TABLE payments ADD COLUMN IF NOT EXISTS amount bigint NOT NULL DEFAULT 0;
ALTER TABLE payments ADD COLUMN IF NOT EXISTS created_at timestamp(6) with time zone NOT NULL DEFAULT now();
ALTER TABLE payments ADD COLUMN IF NOT EXISTS paid_at timestamp(6) with time zone;
ALTER TABLE payments ADD COLUMN IF NOT EXISTS booking_id uuid REFERENCES bookings(id);
ALTER TABLE payments ADD COLUMN IF NOT EXISTS transaction_ref varchar(120);
ALTER TABLE payments ADD COLUMN IF NOT EXISTS method varchar(30) NOT NULL DEFAULT 'CASH_AT_COUNTER';
ALTER TABLE payments ADD COLUMN IF NOT EXISTS status varchar(20) NOT NULL DEFAULT 'UNPAID';

CREATE UNIQUE INDEX IF NOT EXISTS uq_payments_booking_id ON payments (booking_id);

CREATE TABLE IF NOT EXISTS reviews (
    is_featured boolean NOT NULL DEFAULT false,
    rating integer NOT NULL CHECK (rating BETWEEN 1 AND 5),
    created_at timestamp(6) with time zone NOT NULL DEFAULT now(),
    updated_at timestamp(6) with time zone NOT NULL DEFAULT now(),
    booking_id uuid NOT NULL UNIQUE REFERENCES bookings(id),
    customer_id uuid NOT NULL REFERENCES users(id),
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    after_image_url varchar(500),
    before_image_url varchar(500),
    comment text,
    PRIMARY KEY (id)
);

ALTER TABLE reviews ADD COLUMN IF NOT EXISTS is_featured boolean NOT NULL DEFAULT false;
ALTER TABLE reviews ADD COLUMN IF NOT EXISTS rating integer NOT NULL DEFAULT 5;
ALTER TABLE reviews ADD COLUMN IF NOT EXISTS created_at timestamp(6) with time zone NOT NULL DEFAULT now();
ALTER TABLE reviews ADD COLUMN IF NOT EXISTS updated_at timestamp(6) with time zone NOT NULL DEFAULT now();
ALTER TABLE reviews ADD COLUMN IF NOT EXISTS booking_id uuid REFERENCES bookings(id);
ALTER TABLE reviews ADD COLUMN IF NOT EXISTS customer_id uuid REFERENCES users(id);
ALTER TABLE reviews ADD COLUMN IF NOT EXISTS after_image_url varchar(500);
ALTER TABLE reviews ADD COLUMN IF NOT EXISTS before_image_url varchar(500);
ALTER TABLE reviews ADD COLUMN IF NOT EXISTS comment text;

CREATE TABLE IF NOT EXISTS violation_records (
    penalty_points integer NOT NULL DEFAULT 0,
    created_at timestamp(6) with time zone NOT NULL DEFAULT now(),
    booking_id uuid NOT NULL REFERENCES bookings(id),
    customer_id uuid NOT NULL REFERENCES users(id),
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    type varchar(30) NOT NULL,
    note varchar(500),
    PRIMARY KEY (id)
);

ALTER TABLE violation_records ADD COLUMN IF NOT EXISTS penalty_points integer NOT NULL DEFAULT 0;
ALTER TABLE violation_records ADD COLUMN IF NOT EXISTS created_at timestamp(6) with time zone NOT NULL DEFAULT now();
ALTER TABLE violation_records ADD COLUMN IF NOT EXISTS booking_id uuid REFERENCES bookings(id);
ALTER TABLE violation_records ADD COLUMN IF NOT EXISTS customer_id uuid REFERENCES users(id);
ALTER TABLE violation_records ADD COLUMN IF NOT EXISTS type varchar(30) NOT NULL DEFAULT 'LATE_CANCEL';
ALTER TABLE violation_records ADD COLUMN IF NOT EXISTS note varchar(500);

CREATE TABLE IF NOT EXISTS slot_holds (
    created_at timestamp(6) with time zone NOT NULL DEFAULT now(),
    expires_at timestamp(6) with time zone NOT NULL,
    slot_time timestamp(6) with time zone NOT NULL,
    customer_id uuid NOT NULL REFERENCES users(id),
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS blog_categories (
    created_at timestamp(6) with time zone NOT NULL DEFAULT now(),
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    name varchar(100) NOT NULL,
    slug varchar(100) NOT NULL UNIQUE,
    description varchar(500),
    PRIMARY KEY (id)
);

ALTER TABLE blog_categories ADD COLUMN IF NOT EXISTS created_at timestamp(6) with time zone NOT NULL DEFAULT now();
ALTER TABLE blog_categories ADD COLUMN IF NOT EXISTS name varchar(100) NOT NULL DEFAULT 'Demo category';
ALTER TABLE blog_categories ADD COLUMN IF NOT EXISTS slug varchar(100);
ALTER TABLE blog_categories ADD COLUMN IF NOT EXISTS description varchar(500);

CREATE UNIQUE INDEX IF NOT EXISTS uq_blog_categories_slug ON blog_categories (slug);

CREATE TABLE IF NOT EXISTS blog_articles (
    view_count integer NOT NULL DEFAULT 0,
    created_at timestamp(6) with time zone NOT NULL DEFAULT now(),
    published_at timestamp(6) with time zone,
    updated_at timestamp(6) with time zone NOT NULL DEFAULT now(),
    author_id uuid NOT NULL REFERENCES users(id),
    category_id uuid NOT NULL REFERENCES blog_categories(id),
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    status varchar(20) NOT NULL CHECK (status IN ('DRAFT','PUBLISHED','HIDDEN')),
    excerpt varchar(500),
    thumbnail_url varchar(500),
    content text NOT NULL,
    slug varchar(255) NOT NULL UNIQUE,
    title varchar(255) NOT NULL,
    PRIMARY KEY (id)
);

ALTER TABLE blog_articles ADD COLUMN IF NOT EXISTS view_count integer NOT NULL DEFAULT 0;
ALTER TABLE blog_articles ADD COLUMN IF NOT EXISTS created_at timestamp(6) with time zone NOT NULL DEFAULT now();
ALTER TABLE blog_articles ADD COLUMN IF NOT EXISTS published_at timestamp(6) with time zone;
ALTER TABLE blog_articles ADD COLUMN IF NOT EXISTS updated_at timestamp(6) with time zone NOT NULL DEFAULT now();
ALTER TABLE blog_articles ADD COLUMN IF NOT EXISTS author_id uuid REFERENCES users(id);
ALTER TABLE blog_articles ADD COLUMN IF NOT EXISTS category_id uuid REFERENCES blog_categories(id);
ALTER TABLE blog_articles ADD COLUMN IF NOT EXISTS status varchar(20) NOT NULL DEFAULT 'DRAFT';
ALTER TABLE blog_articles ADD COLUMN IF NOT EXISTS excerpt varchar(500);
ALTER TABLE blog_articles ADD COLUMN IF NOT EXISTS thumbnail_url varchar(500);
ALTER TABLE blog_articles ADD COLUMN IF NOT EXISTS content text NOT NULL DEFAULT '';
ALTER TABLE blog_articles ADD COLUMN IF NOT EXISTS slug varchar(255);
ALTER TABLE blog_articles ADD COLUMN IF NOT EXISTS title varchar(255) NOT NULL DEFAULT 'Demo article';

CREATE UNIQUE INDEX IF NOT EXISTS uq_blog_articles_slug ON blog_articles (slug);

CREATE TABLE IF NOT EXISTS blog_comments (
    created_at timestamp(6) with time zone NOT NULL DEFAULT now(),
    updated_at timestamp(6) with time zone NOT NULL DEFAULT now(),
    article_id uuid NOT NULL REFERENCES blog_articles(id),
    customer_id uuid NOT NULL REFERENCES users(id),
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    content text NOT NULL,
    PRIMARY KEY (id)
);

ALTER TABLE blog_comments ADD COLUMN IF NOT EXISTS created_at timestamp(6) with time zone NOT NULL DEFAULT now();
ALTER TABLE blog_comments ADD COLUMN IF NOT EXISTS updated_at timestamp(6) with time zone NOT NULL DEFAULT now();
ALTER TABLE blog_comments ADD COLUMN IF NOT EXISTS article_id uuid REFERENCES blog_articles(id);
ALTER TABLE blog_comments ADD COLUMN IF NOT EXISTS customer_id uuid REFERENCES users(id);
ALTER TABLE blog_comments ADD COLUMN IF NOT EXISTS content text NOT NULL DEFAULT '';

CREATE TABLE IF NOT EXISTS blog_likes (
    created_at timestamp(6) with time zone NOT NULL DEFAULT now(),
    article_id uuid NOT NULL REFERENCES blog_articles(id),
    customer_id uuid NOT NULL REFERENCES users(id),
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    PRIMARY KEY (id)
);

ALTER TABLE blog_likes ADD COLUMN IF NOT EXISTS created_at timestamp(6) with time zone NOT NULL DEFAULT now();
ALTER TABLE blog_likes ADD COLUMN IF NOT EXISTS article_id uuid REFERENCES blog_articles(id);
ALTER TABLE blog_likes ADD COLUMN IF NOT EXISTS customer_id uuid REFERENCES users(id);

CREATE TABLE IF NOT EXISTS announcements (
    active boolean NOT NULL DEFAULT true,
    priority integer NOT NULL DEFAULT 0,
    created_at timestamp(6) with time zone NOT NULL DEFAULT now(),
    expires_at timestamp(6) with time zone,
    updated_at timestamp(6) with time zone NOT NULL DEFAULT now(),
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    type varchar(30) NOT NULL,
    link_label varchar(100),
    link_url varchar(500),
    message text,
    title varchar(255) NOT NULL,
    PRIMARY KEY (id)
);

ALTER TABLE announcements ADD COLUMN IF NOT EXISTS active boolean NOT NULL DEFAULT true;
ALTER TABLE announcements ADD COLUMN IF NOT EXISTS priority integer NOT NULL DEFAULT 0;
ALTER TABLE announcements ADD COLUMN IF NOT EXISTS created_at timestamp(6) with time zone NOT NULL DEFAULT now();
ALTER TABLE announcements ADD COLUMN IF NOT EXISTS expires_at timestamp(6) with time zone;
ALTER TABLE announcements ADD COLUMN IF NOT EXISTS updated_at timestamp(6) with time zone NOT NULL DEFAULT now();
ALTER TABLE announcements ADD COLUMN IF NOT EXISTS type varchar(30) NOT NULL DEFAULT 'SYSTEM';
ALTER TABLE announcements ADD COLUMN IF NOT EXISTS link_label varchar(100);
ALTER TABLE announcements ADD COLUMN IF NOT EXISTS link_url varchar(500);
ALTER TABLE announcements ADD COLUMN IF NOT EXISTS message text;
ALTER TABLE announcements ADD COLUMN IF NOT EXISTS title varchar(255) NOT NULL DEFAULT 'Announcement';

CREATE TABLE IF NOT EXISTS notification_campaigns (
    failed_count integer NOT NULL DEFAULT 0,
    success_count integer NOT NULL DEFAULT 0,
    created_at timestamp(6) with time zone NOT NULL DEFAULT now(),
    scheduled_at timestamp(6) with time zone,
    sent_at timestamp(6) with time zone,
    updated_at timestamp(6) with time zone NOT NULL DEFAULT now(),
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    status varchar(20) NOT NULL CHECK (status IN ('DRAFT','SCHEDULED','SENDING','COMPLETED','FAILED')),
    target_audience varchar(30) NOT NULL CHECK (target_audience IN ('ALL_CUSTOMERS','TIER_BRONZE','TIER_SILVER','TIER_GOLD','TIER_PLATINUM','TIER_DIAMOND','INDIVIDUALS')),
    type varchar(30) NOT NULL CHECK (type IN ('BOOKING_CREATED','BOOKING_CONFIRMED','WASH_CHECKED_IN','WASH_COMPLETED','BOOKING_REMINDER','NO_SHOW','LOYALTY','VOUCHER_EXPIRY','SYSTEM','PROMOTION')),
    title varchar(150) NOT NULL,
    message text NOT NULL,
    target_details text,
    PRIMARY KEY (id)
);

ALTER TABLE notification_campaigns ADD COLUMN IF NOT EXISTS failed_count integer NOT NULL DEFAULT 0;
ALTER TABLE notification_campaigns ADD COLUMN IF NOT EXISTS success_count integer NOT NULL DEFAULT 0;
ALTER TABLE notification_campaigns ADD COLUMN IF NOT EXISTS created_at timestamp(6) with time zone NOT NULL DEFAULT now();
ALTER TABLE notification_campaigns ADD COLUMN IF NOT EXISTS scheduled_at timestamp(6) with time zone;
ALTER TABLE notification_campaigns ADD COLUMN IF NOT EXISTS sent_at timestamp(6) with time zone;
ALTER TABLE notification_campaigns ADD COLUMN IF NOT EXISTS updated_at timestamp(6) with time zone NOT NULL DEFAULT now();
ALTER TABLE notification_campaigns ADD COLUMN IF NOT EXISTS status varchar(20) NOT NULL DEFAULT 'DRAFT';
ALTER TABLE notification_campaigns ADD COLUMN IF NOT EXISTS target_audience varchar(30) NOT NULL DEFAULT 'ALL_CUSTOMERS';
ALTER TABLE notification_campaigns ADD COLUMN IF NOT EXISTS type varchar(30) NOT NULL DEFAULT 'SYSTEM';
ALTER TABLE notification_campaigns ADD COLUMN IF NOT EXISTS title varchar(150) NOT NULL DEFAULT 'Notification campaign';
ALTER TABLE notification_campaigns ADD COLUMN IF NOT EXISTS message text NOT NULL DEFAULT '';
ALTER TABLE notification_campaigns ADD COLUMN IF NOT EXISTS target_details text;

CREATE TABLE IF NOT EXISTS notifications (
    is_read boolean NOT NULL DEFAULT false,
    created_at timestamp(6) with time zone NOT NULL DEFAULT now(),
    campaign_id uuid REFERENCES notification_campaigns(id),
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    user_id uuid NOT NULL REFERENCES users(id),
    type varchar(30) NOT NULL CHECK (type IN ('BOOKING_CREATED','BOOKING_CONFIRMED','WASH_CHECKED_IN','WASH_COMPLETED','BOOKING_REMINDER','NO_SHOW','LOYALTY','VOUCHER_EXPIRY','SYSTEM','PROMOTION')),
    title varchar(150) NOT NULL,
    message varchar(255) NOT NULL,
    PRIMARY KEY (id)
);

ALTER TABLE notifications ADD COLUMN IF NOT EXISTS is_read boolean NOT NULL DEFAULT false;
ALTER TABLE notifications ADD COLUMN IF NOT EXISTS created_at timestamp(6) with time zone NOT NULL DEFAULT now();
ALTER TABLE notifications ADD COLUMN IF NOT EXISTS campaign_id uuid REFERENCES notification_campaigns(id);
ALTER TABLE notifications ADD COLUMN IF NOT EXISTS user_id uuid REFERENCES users(id);
ALTER TABLE notifications ADD COLUMN IF NOT EXISTS type varchar(30) NOT NULL DEFAULT 'SYSTEM';
ALTER TABLE notifications ADD COLUMN IF NOT EXISTS title varchar(150) NOT NULL DEFAULT 'Notification';
ALTER TABLE notifications ADD COLUMN IF NOT EXISTS message varchar(255) NOT NULL DEFAULT '';

CREATE INDEX IF NOT EXISTS idx_notifications_user_id ON notifications (user_id);
