spring.config.import=optional:file:./.env[.properties],optional:file:./autowash-backend/.env[.properties]

spring.datasource.url=${AUTOWASH_DB_URL:jdbc:postgresql://localhost:5432/autowash}
spring.datasource.username=${AUTOWASH_DB_USERNAME:postgres}
spring.datasource.password=${AUTOWASH_DB_PASSWORD:123456}
spring.datasource.driver-class-name=${AUTOWASH_DB_DRIVER_CLASS_NAME:org.postgresql.Driver}

spring.jpa.database-platform=${SPRING_JPA_DATABASE_PLATFORM:org.hibernate.dialect.PostgreSQLDialect}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.hbm2ddl.auto=validate

spring.flyway.locations=classpath:db/migration,classpath:db/demo

autowash.auth.google.dev-bypass-enabled=false
